### ISSUE TITLE
Congratulations for the great work

### ISSUE THREAD

**Issue by Juasmis** [saurontech/Advantech-VCOM-Linux-Driver#45]
This is not an issue but just wanted to thank the author of this repository and the company. Usually industrial devices and communications are Windows only and it was a breath of fresh air discovering a company that not only had a linux driver but that have been actively maintaining for so many years and open sourcing it.

I am only a PhD student but I will always recommend the instrumentation department of my company or any colleagues to buy your products.

Keep up the good work! 👍

**Comment by saurontech** [comment]
Thanks for the encouragement.
Really appreciate it.
